### PR TITLE
Added setup files for pypi submission

### PR DESCRIPTION
**Pull request by lhl**
Hey Daniel, saw this wrapper and was going to give it a try, but it'd be more useful if it was in pypi?
I've added the setup files to give that a bit of a push.

For a simple guide on adding packages to pypi (it's not too bad):
http://peterdowns.com/posts/first-time-with-pypi.html
https://packaging.python.org/distributing/
https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/

### CODE REVIEW

**Comment by danpaquin** [comment]
Awesome! I will work on this and hopefully submit the app to pypi this week if all goes well.

**Comment by lhl** [comment]
OK, if you merge this pull request it will get you most of the way there.

**Comment by danpaquin** [comment]
Thanks again, I would like to add the rest of the files I need later this week and then merge once it's ready to be updated.

**Comment by lhl** [comment]
OK, it might be better to merge now since this pull request I think is applying master to master. I am checking in changes to make this Python 3 compatible...

**Comment by danpaquin** [comment]
Would it also require that I add brackets to the print statements?

**Comment by lhl** [comment]
Well, depends on if I get to it first or not I guess. It'd be better to merge these non-conflicting changes first, will make life easier for the other changes that will probably be a bit more invasive. My plan is to make changes over the next day or two...

**Pull request merged**
